### PR TITLE
Added SEO/page descriptions

### PR DESCRIPTION
**Pull request by Jaykocha**
Please give me some feedback: Should the short descriptions always be full sentences? So f.e. I wrote "[...]. List of fullnodes." Would it maybe be better to write "See a list of fullnodes"?

### CODE REVIEW

**Comment by 0ptim** [comment]
I think it's great. I'm not quite sure what's the best way for SEO. Would need to read up on it as well.

But I think for now it does not really matter. Any description is better than no description.

Thanks a lot for your work! 🚀

PS: Found you on Twitter 😛

**Comment by Jaykocha** [comment]
Nice! I followed you back just now ;)

Ok, I will continue to work through it and finish it all soon. When I see something that I am questioning or some broken links or whatever, I will create some issues. That is why it will probably take a week or so, but I really want to read the whole pages to deepen my understanding for DeFiChain.

**Comment by 0ptim** [comment]
This is awesome! Very useful if we have a list of tasks which can be tracked.

**Comment by Jaykocha** [comment]
So I am done with the short descriptions. So feel free to merge it :)

**Comment by 0ptim** [comment]
Thank you so much! That was awesome work, right there!

**Pull request merged**
